export const Category = { Men: 'Men', Women: 'Women', Kids: 'Kids' };

export const CardsData = {
  Men: [
    {
      product_id: 1,
      product_image: 'images/big-shoe1.png',
      product_name: 'Apple Watch',
      product_price: 1,
      desc: 'Stay connected and track your fitness with the Apple Watch Series 7, featuring a sleek Aluminium case and GPS functionality.',
    },
    {
      product_id: 2,
      product_image: 'images/big-shoe1.png',
      product_name: 'Apple Watch Series 7 GPS, Aluminium Case, Starlight Sport',
      product_price: 599,
      desc: 'A perfect blend of style and technology, the Series 7 is designed to help you achieve your health and fitness goals.',
    },
    {
      product_id: 3,
      product_image: 'images/big-shoe2.png',
      product_name: 'Apple Watch Series 7 GPS, Aluminium Case, Starlight Sport',
      product_price: 599,
      desc: 'The Apple Watch Series 7 is your all-in-one companion for fitness tracking, notifications, and personal health insights.',
    },
    {
      product_id: 4,
      product_image: 'images/big-shoe3.png',
      product_name: 'Apple Watch Series 7 GPS, Aluminium Case, Starlight Sport',
      product_price: 599,
      desc: 'A modern smartwatch with a larger display, faster charging, and enhanced durability for active lifestyles.',
    },
    {
      product_id: 5,
      product_image: 'images/clo-1.jpeg',
      product_name: 'Apple Watch Series 7 GPS, Aluminium Case, Starlight Sport',
      product_price: 599,
      desc: 'Designed for both style and function, the Apple Watch Series 7 comes with powerful health features and is built to last.',
    },
  ],
  Women: [
    {
      product_id: 6,
      product_image: 'images/clo-2.jpeg',
      product_name: 'Apple Watch Women Category',
      product_price: 899,
      desc: 'A stylish and versatile smartwatch made for women who want to stay connected while maintaining elegance.',
    },
    {
      product_id: 7,
      product_image: 'images/clo-3.jpeg',
      product_name: 'Apple Watch Women Category',
      product_price: 899,
      desc: 'With its refined design, the Apple Watch for women combines beauty with cutting-edge technology.',
    },
    {
      product_id: 8,
      product_image: 'images/clo-3.jpeg',
      product_name: 'Apple Watch Women Category',
      product_price: 899,
      desc: 'A premium smartwatch crafted for modern women, offering features that enhance your health and lifestyle.',
    },
    {
      product_id: 9,
      product_image: 'images/clo-3.jpeg',
      product_name: 'Apple Watch Women Category',
      product_price: 899,
      desc: 'Designed with elegance in mind, this Apple Watch offers practical features to help you manage your day.',
    },
    {
      product_id: 10,
      product_image: 'images/clo-3.jpeg',
      product_name: 'Apple Watch Women Category',
      product_price: 899,
      desc: 'A perfect accessory for any woman, the Apple Watch combines fashion with advanced health tracking technology.',
    },
  ],
  Kids: [
    {
      product_id: 11,
      product_image: 'images/gun-2.jpeg',
      product_name: 'Apple Watch Kids Category',
      product_price: 999,
      desc: 'A kid-friendly smartwatch designed to keep your child connected, while also tracking their fitness and health.',
    },
    {
      product_id: 12,
      product_image: 'images/gun-2.jpeg',
      product_name: 'Apple Watch Kids Category',
      product_price: 999,
      desc: 'The Apple Watch for kids offers a durable design, educational features, and parental controls for safety.',
    },
    {
      product_id: 13,
      product_image: 'images/gun-2.jpeg',
      product_name: 'Apple Watch Kids Category',
      product_price: 999,
      desc: 'With a playful design and kid-friendly features, this smartwatch helps your child stay active and connected.',
    },
    {
      product_id: 14,
      product_image: 'images/gun-2.jpeg',
      product_name: 'Apple Watch Kids Category',
      product_price: 999,
      desc: 'An ideal watch for children, offering fun features while allowing parents to keep track of their activities and location.',
    },
    {
      product_id: 15,
      product_image: 'images/gun-2.jpeg',
      product_name: 'Apple Watch Kids Category',
      product_price: 999,
      desc: 'Built for active kids, this Apple Watch offers robust protection and features designed for younger users.',
    },
  ],
};
